clickhouse:
  # if true k8s will create LoadBalancer for port 8123
  lbEnabled: false
  # installs clickhouse-client
  withClient: true
  replicaCount: 2
  # You can build and deploy to your registry
  repository: pltvs/clickhouse-server
  tag: latest
  pullPolicy: Always
  cpuLimit: 125m
  memoryLimit: 256Mi
  disk: 256Mi
  writerPass: 2c82mirS
  readerPass: gFzFTUQ9

zookeeper:
  replicaCount: 2
  cpuLimit: 125m
  memoryLimit: 128Mi
  disk: 256Mi

# tabix.io web UI
tabix:
  enabled: false
  lbEnabled: false

# Add monitoring with graphite
graphite:
  enabled: false
  lbEnabled: false