clickhouse:
  replicaCount: 2
  repository: pltvs/clickhouse-server
  tag: latest
  pullPolicy: Always
  disk: 256Mi
  writerPass: 2c82mirS
  readerPass: gFzFTUQ9
  lb:
    enabled: false
    restPort: 8123
    rpcPort: 9000
  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi

  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  ## Affinity
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  ## Tolerations
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  ## updateStrategy for MongoDB Primary, Secondary and Arbitrer statefulsets
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  updateStrategy:
    type: RollingUpdate

# deploys clickhouse-client
client:
  enabled: true

# zookeeper
zookeeper:
  repository: gcr.io/google_samples/k8szk
  tag: v1
  replicaCount: 2
  disk: 256Mi
  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi

# tabix.io web UI
tabix:
  enabled: false
  lb:
    enabled: false
    port: 8088

# monitoring with graphite
graphite:
  enabled: false
  lb:
    enabled: false
    port: 8080
