apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: rpc
  - port: 8123
    name: rest
  - port: 9009
    name: interserver
  clusterIP: None
  selector:
    app: clickhouse

{{ if .Values.clickhouse.lbEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-lb
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 8123
    targetPort: 8123
  - name: rpc
    port: 9000
    targetPort: 9000
  selector:
    app: clickhouse
{{ end }}